### ISSUE TITLE
automatically send an introduction email to every crawled result

### ISSUE THREAD

**Issue by mischkew** [adriankumpf/findmeaflat#3]

**Comment by adriankumpf** [comment]
Thanks for using findmeaflat! Great to see other people using it :)

Since I've recently found a flat (which I wouldn't have gotten without this application), I don't have the it running anymore. And thus, I don't have the use case for it. BUT I would like to see a PR from you!

A good starting point would be to add an email "channel" to `lib/services/notify.js`. Then, depending on the configuration, an email as well as a telegram notification could be sent for every new listing.

**Comment by mischkew** [comment]
Hey Adrian,

yeah great work indeed. The issues I created should have been on my fork :) I will investigate this further, once I find the time.
